# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20160705_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('born', models.IntegerField(null=True)),
                ('died', models.IntegerField(null=True)),
                ('artist_description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('edition', models.CharField(blank=True, max_length=128)),
                ('series', models.CharField(blank=True, max_length=128)),
                ('stock', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='LoanIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_in_id', models.CharField(blank=True, max_length=128, unique=True)),
                ('loan_in_date', models.DateField(blank=True)),
                ('lender', models.CharField(blank=True, max_length=128)),
                ('return_out_date', models.DateField(blank=True)),
                ('loan_in_note', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LoanOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_out_id', models.CharField(blank=True, max_length=128, unique=True)),
                ('loan_out_date', models.DateField(blank=True)),
                ('borrower', models.CharField(blank=True, max_length=128)),
                ('return_in_date', models.DateField(blank=True)),
                ('loan_out_note', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.RemoveField(
            model_name='description',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='description',
            name='item',
        ),
        migrations.RemoveField(
            model_name='description',
            name='material',
        ),
        migrations.RemoveField(
            model_name='description',
            name='series',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.RemoveField(
            model_name='location',
            name='item',
        ),
        migrations.RemoveField(
            model_name='production',
            name='item',
        ),
        migrations.RemoveField(
            model_name='production',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='item',
        ),
        migrations.AddField(
            model_name='description',
            name='depth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='item_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='description',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='entry',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Item'),
        ),
        migrations.AddField(
            model_name='exit',
            name='exit_id',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Description'),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='production',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Production'),
        ),
        migrations.AddField(
            model_name='item',
            name='usage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Usage'),
        ),
        migrations.AddField(
            model_name='production',
            name='production_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='condition',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_id',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='owner',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='exit',
            name='exit_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='exit',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Artist'),
        ),
        migrations.AlterField(
            model_name='production',
            name='place',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='production',
            name='technique',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='usage',
            name='status',
            field=models.CharField(blank=True, choices=[('DP', 'On Display'), ('SR', 'In Storage'), ('LN', 'On Loan'), ('EX', 'Exit')], max_length=2),
        ),
        migrations.AddField(
            model_name='loanout',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Item'),
        ),
        migrations.AddField(
            model_name='loanin',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Item'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='identification',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Identification'),
        ),
    ]
