# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20160706_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='item_description',
        ),
        migrations.AddField(
            model_name='description',
            name='subject',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='description',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='description',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='description',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='description',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
