# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20160707_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='born',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='died',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
