# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20160709_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cms.Item'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='cms.Item'),
        ),
        migrations.AlterField(
            model_name='loanin',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_ins', to='cms.Item'),
        ),
        migrations.AlterField(
            model_name='loanout',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_outs', to='cms.Item'),
        ),
    ]
