# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
