# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20160710_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='note',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
