# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160811_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_description',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
